Traceback (most recent call last):
  File "/home/sadbhawna/Desktop/cs6910_assignment1/train.py", line 121, in <module>
    train_arguments(args) # python train.py --dataset mnist --epochs 100 -nhl 3 -sz 64
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sadbhawna/Desktop/cs6910_assignment1/train.py", line 96, in train_arguments
    fit(layer_architecture, X_train, Y_train, X_val, Y_val, X_test, Y_test, epochs=20, activation='relu', loss = 'cross_entropy', optimizer='nadam', weight_ini = 'He Normal',learning_rate=0.0001, batch=256, weight_decay=0.0, epsilon=1e-6, project=args.wandb_project)
  File "/home/sadbhawna/Desktop/cs6910_assignment1/train.py", line 32, in fit
    Nadam(layer_architecture, X_train, Y_train, X_val, Y_val, X_test, Y_test, epochs=epochs, activation=activation, loss=loss, weight_ini = weight_ini, learning_rate=learning_rate, beta1=beta1, beta2=beta2, batch=batch, epsilon=epsilon, weight_decay=weight_decay)
  File "/home/sadbhawna/Desktop/cs6910_assignment1/optimizers.py", line 358, in Nadam
    HL, previous_store = nn.forward_propagation(X)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sadbhawna/Desktop/cs6910_assignment1/Feedforward_Neural_Network.py", line 78, in forward_propagation
    A = np.dot(self.parameters['W' + str(l)], H_prev) + self.parameters['b' + str(l)]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in dot
ValueError: shapes (32,128) and (784,256) not aligned: 128 (dim 1) != 784 (dim 0)